#Version: 1.4
#Author: T0X1C
messages:
  only-players: "&6&lRename&e&l+ &8> &7Only players can perform this command!"
  no-permissions: "&6&lRename&e&l+ &8> &4You don't have permissions!"
  no-colors: "&6&lRename&e&l+ &8> &4You don't have permissions to use colors!"
  inappropriate-words: "&6&lRename&e&l+ &8> &4Did not succeed because the name/lore contains a inappropriate word!"
  
  rename-usage: "&6&lRename&e&l+ &8> &7/rename <name>"
  rename-max-length: "&6&lRename&e&l+ &8> &4You have reached the max length of characters! &7(&c%amount%&7/&c%maxamount%&7)"
  cannot-rename-air: "&6&lRename&e&l+ &8> &4You must have an item in your hand!"
  successfully-renamed: "&6&lRename&e&l+ &8> &7You have successfully renamed your item! &8(&c%name%&8)"
  
  addlore-usage: "&6&lRename&e&l+ &8> &7/addlore <lore>"
  addlore-max-length: "&6&lRename&e&l+ &8> &4You have reached the max length of characters! &7(&c%amount%&7/&c%maxamount%&7)"
  cannot-addlore-air: "&6&lRename&e&l+ &8> &4You must have an item in your hand!"
  successfully-added-lore: "&6&lRename&e&l+ &8> &7You have successfully added a lore to your item! &8(&c%lore%&8)"
  
  setlore-usage: "&6&lRename&e&l+ &8> &7/setlore <lore>"
  setlore-max-length: "&6&lRename&e&l+ &8> &4You have reached the max length of characters! &7(&c%amount%&7/&c%maxamount%&7)"
  cannot-setlore-air: "&6&lRename&e&l+ &8> &4You must have an item in your hand!"
  successfully-setlore: "&6&lRename&e&l+ &8> &7You have successfully added set the lore of your item! &8(&c%lore%&8)"

  removelore-usage: "&6&lRename&e&l+ &8> &7/removelore <number>"
  cannot-removelore-air: "&6&lRename&e&l+ &8> &4You must have an item in your hand!"
  invalid-lore-number: "&6&lRename&e&l+ &8> &4Invalid lore number (&7Your item only has &4%amount% &7lores&4)"
  no-lore: "&6&lRename&e&l+ &8> &4Your item has no lore!"
  no-: "&6&lRename&e&l+ &8> &4You cannot use -"
  no-0: "&6&lRename&e&l+ &8> &4Why would you remove the line 0 of the lore?"
  successfully-removedlore: "&6&lRename&e&l+ &8> &7You have successfully removed the line &c%line% &7from the lore of your item! &8(&c%lore%&8)"

sounds:
  #If it should play a sound
  enabled: true
  #When they try to rename it to a inappropriate word
  #Note: here's a list of all sounds https://github.com/Bukkit/Bukkit/blob/master/src/main/java/org/bukkit/Sound.java
  inappropriate-words: VILLAGER_NO
  no-permissions: VILLAGER_NO
  success: VILLAGER_YES

settings:
  #Note &6 or any color codes is = 2 (like & = 1.. and &3 = 2)
  rename-max-length: 24
  addlore-max-length: 36
  setlore-max-length: 36

#Ok so let's say you have 'Nigger' then it would also block 'NiGgEr', 'NigGeR'
banned-words:
  - 'Nigger'
  - 'N1gger'
  - 'Nigg3r'
  - 'N1gg3r'
  - 'nigga'
  - 'n1gga'
  - 'niga'
  - 'n1ga'
  - 'fuck'
  - 'fuk'
  - 'fuq'
  - 'bitch'
  - 'b1tch'
  - 'bich'
  - 'KKK'
  - 'Hitler'
  - 'H1tler'
  - 'H1tl3r'
  - 'Nazi'
  - 'Naz1'