#Version: 1.3
#Author: T0X1C
Messages:
  OnlyPlayers: "&6&lRename&e&l+ &8> &7Only players can perform this command!"
  NoPermissions: "&6&lRename&e&l+ &8> &4You don't have permissions!"
  NoColors: "&6&lRename&e&l+ &8> &4You don't have permissions to use colors!"
  InappropriateWords: "&6&lRename&e&l+ &8> &4Did not succeed because the name/lore contains a inappropriate word!"
  
  RenameUsage: "&6&lRename&e&l+ &8> &7/rename <name>"
  RenameMaxLength: "&6&lRename&e&l+ &8> &4You have reached the max length of characters! &7(&c%amount%&7/&c%maxamount%&7)"
  CannotRenameAir: "&6&lRename&e&l+ &8> &4You must have an item in your hand!"
  SuccessfullyRenamed: "&6&lRename&e&l+ &8> &7You have successfully renamed your item!"
  
  AddloreUsage: "&6&lRename&e&l+ &8> &7/addlore <lore>"
  AddloreMaxLength: "&6&lRename&e&l+ &8> &4You have reached the max length of characters! &7(&c%amount%&7/&c%maxamount%&7)"
  CannotAddloreAir: "&6&lRename&e&l+ &8> &4You must have an item in your hand!"
  SuccessfullyAddedlore: "&6&lRename&e&l+ &8> &7You have successfully added a lore to your item!"
  
  SetloreUsage: "&6&lRename&e&l+ &8> &7/setlore <lore>"
  SetloreMaxLength: "&6&lRename&e&l+ &8> &4You have reached the max length of characters! &7(&c%amount%&7/&c%maxamount%&7)"
  CannotSetloreAir: "&6&lRename&e&l+ &8> &4You must have an item in your hand!"
  SuccessfullySetlore: "&6&lRename&e&l+ &8> &7You have successfully added set the lore of your item!"

  RemoveloreUsage: "&6&lRename&e&l+ &8> &7/removelore <number>"
  CannotRemoveloreAir: "&6&lRename&e&l+ &8> &4You must have an item in your hand!"
  InvalidLoreNumber: "&6&lRename&e&l+ &8> &4Invalid lore number (&7Your item only has &4%amount% &7lores&4)"
  NoLore: "&6&lRename&e&l+ &8> &4Your item has no lore!"
  No-: "&6&lRename&e&l+ &8> &4You cannot use -"
  No0: "&6&lRename&e&l+ &8> &4Why would you remove the line 0 of the lore?"
  SuccessfullyRemovedlore: "&6&lRename&e&l+ &8> &7You have successfully removed the line &c%line% &7from the lore of your item!"

Sounds:
  #If it should play a sound
  Enabled: true
  #When they try to rename it to a inappropriate word
  #Note: here's a list of all sounds https://github.com/Bukkit/Bukkit/blob/master/src/main/java/org/bukkit/Sound.java
  InappropriateWords: VILLAGER_NO
  NoPermissions: VILLAGER_NO
  Success: VILLAGER_YES

Settings:
  #Note &6 or any color codes is = 2 (like & = 1.. and &3 = 2)
  RenameMaxLength: 24
  AddloreMaxLength: 36
  SetloreMaxLength: 36

#Ok so let's say you have 'Nigger' then it would also block 'NiGgEr', 'NigGeR'
Banned-Words:
  - 'Nigger'
  - 'N1gger'
  - 'Nigg3r'
  - 'N1gg3r'
  - 'nigga'
  - 'n1gga'
  - 'niga'
  - 'n1ga'
  - 'fuck'
  - 'fuk'
  - 'fuq'
  - 'bitch'
  - 'b1tch'
  - 'bich'
  - 'KKK'
  - 'Hitler'
  - 'H1tler'
  - 'H1tl3r'
  - 'Nazi'
  - 'Naz1'