name: RenamePlus
main: me.t0x1c.renameplus.Main
version: 1.4
author: T0X1C

commands:
    rename:
        description: Rename your item you have in your hands
    addlore:
        description: Add another lore to your item
    setlore:
        description: Set the lore of your item
    removelore:
        description: Remove a specific line from the lore of your item

permissions:
    RenamePlus.rename:
        default: op

    RenamePlus.colors:
        default: op

    RenamePlus.addlore:
        default: op

    RenamePlus.setlore:
        default: op